version: '3'
services:
  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      DASHBOARD_URL: http://localhost:8080
      DIRECTOR_URL: http://localhost:1234
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://mongo:27017/sorry-cypress'
      STORAGE_DRIVER: '../execution/minio/driver'
      MINIO_ACCESS_KEY: 'key'
      MINIO_SECRET_KEY: 'secret'
      MINIO_ENDPOINT: 'minio'
      MINIO_PORT: 9000
      MINIO_BUCKET: sorry-cypress
    ports:
      - '1234:1234'
    depends_on:
      - mongo
      - minio

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://mongo:27017/sorry-cypress'
    ports:
      - '4000:4000'
    depends_on:
      - mongo

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://localhost:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
    ports:
      - '8080:8080'
    depends_on:
      - api

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - ./data/data-mongo-cypress:/data/db

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: 'key'
      MINIO_SECRET_KEY: 'secret'
    ports:
      - '9000:9000'
    volumes:
      - ./data/data-minio-cypress:/data
    command: server /data